#!/usr/bin/env node
/**
 * Generate the request list for fine-tuning: ~450 distinct, natural-sounding
 * UI requests across the six blueprint families plus free-form ones, with a
 * stratified 50-prompt hold-out that also contains the six workbench sparks.
 * Deterministic (seeded), so the list can be regenerated byte for byte.
 *
 *   node training/scripts/make-prompts.mjs > training/data/prompts.jsonl
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const OUT = process.argv[2] ?? new URL('../data/prompts.jsonl', import.meta.url).pathname;
let seed = 20260910;
const rand = () => { seed |= 0; seed = (seed + 0x6d2b79f5) | 0; let t = Math.imul(seed ^ (seed >>> 15), 1 | seed); t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t; return ((t ^ (t >>> 14)) >>> 0) / 4294967296; };
const pick = (list) => list[Math.floor(rand() * list.length)];
const some = (list, min, max) => { const n = min + Math.floor(rand() * (max - min + 1)); const pool = [...list]; const out = []; while (out.length < n && pool.length) out.push(pool.splice(Math.floor(rand() * pool.length), 1)[0]); return out; };
const join = (items) => items.length <= 1 ? items.join('') : `${items.slice(0, -1).join(', ')}, and ${items.at(-1)}`;

const domains = ['a neighborhood bakery', 'a bike repair shop', 'a dental clinic', 'a veterinary clinic', 'a yoga studio', 'a coffee roaster', 'an indie bookstore', 'a community garden', 'a climbing gym', 'a taco truck', 'a wedding planner', 'a tattoo studio', 'a podcast network', 'the city library', 'a farmers market', 'a ski resort', 'a public aquarium', 'a robotics club', 'a board game cafe', 'a car wash', 'a dog walking service', 'a houseplant nursery', 'a home solar installer', 'a chess tournament', 'a city marathon', 'a film festival', 'an escape room', 'a pottery studio', 'a sailing school', 'a beekeeping co-op', 'a hospice volunteer program', 'a university admissions office', 'a high school science fair', 'a local newspaper', 'a food bank', 'an animal shelter', 'a music school', 'a tiny house builder', 'a vintage camera repair shop', 'a craft brewery', 'a hot sauce startup', 'a drone photography studio', 'a translation agency', 'a math tutoring service', 'a bicycle courier company', 'a laundromat', 'an ice rink', 'a recording studio', 'a surf school', 'a mushroom farm', 'a neighborhood watch group', 'a retro arcade', 'a dance company', 'a tea house', 'a comic shop', 'a plumbing company', 'a harbor ferry service', 'a museum gift shop', 'an astronomy club', 'a ceramics supply store'];

const formKinds = ['intake', 'registration', 'booking', 'feedback', 'application', 'RSVP', 'onboarding', 'contact', 'sign-up', 'return request', 'quote request', 'volunteer application', 'incident report', 'membership renewal'];
const formFields = ['full name', 'email address', 'phone number', 'preferred date', 'preferred time', 'a short description of the issue', 'number of guests', 'dietary restrictions', 'emergency contact', 'date of birth', 'street address', 'a how-did-you-hear-about-us dropdown', 'experience level', 'membership tier', 'a comments box', 'company name', 'budget range', 'preferred contact method', 'accessibility needs', 'a consent checkbox described as a field', 'vehicle make and model', 'pet name and breed', 'instrument played', 'shoe size', 'a reason for cancelling', 'order number', 'preferred language'];
const submitLabels = ['submit button', 'save button', 'send request button', 'book now button', 'register button', 'apply button', 'confirm button'];
const formTone = ['plain and professional', 'friendly', 'compact', 'formal', 'welcoming', 'minimal', 'clear and calm'];

const chatParties = [['a customer', 'a support agent'], ['a patient', 'the front desk'], ['a student', 'a tutor'], ['a rider', 'a dispatcher'], ['a guest', 'the host'], ['a member', 'a coach'], ['a buyer', 'the seller'], ['a parent', 'a teacher'], ['a tenant', 'the landlord'], ['a volunteer', 'the coordinator']];
const chatTopics = ['a delayed order', 'a double-booked appointment', 'a refund for a damaged item', 'rescheduling a lesson', 'a lost package', 'a billing mistake', 'a noise complaint', 'an allergy question about the menu', 'a broken locker', 'changing a reservation date', 'a missing certificate', 'a late delivery fee', 'access to a members-only class', 'a password reset that keeps failing'];
const chatEndings = ['a proposed solution', 'an apology and a credit', 'a confirmed new time', 'a promise to call back', 'a link to the policy', 'an escalation to a manager', 'a resolved ticket'];
const chatLength = ['a short back-and-forth', 'four or five messages', 'a brief exchange', 'a quick conversation', 'a six-message thread'];

const dashKinds = ['status dashboard', 'operations dashboard', 'weekly report', 'health overview', 'progress tracker', 'live monitor', 'morning briefing', 'KPI board'];
const dashMetrics = ['revenue this month', 'open tickets', 'active members', 'orders shipped today', 'average wait time', 'inventory on hand', 'bookings this week', 'churn rate', 'volunteer hours logged', 'website visits', 'conversion rate', 'donations received', 'seats filled', 'units produced', 'response time', 'satisfaction score', 'budget used', 'tasks completed', 'temperature and humidity', 'uptime', 'deliveries on time', 'new sign-ups', 'refunds issued', 'classes at capacity'];
const dashExtras = ['a blockers alert', 'a progress bar toward the quarterly goal', 'a list of overdue items', 'a status badge for each team', 'a warning when stock runs low', 'a countdown to the next event', 'a note about the biggest risk', 'a progress bar per project'];
const dashActions = ['view the full report', 'export to CSV', 'open the board', 'acknowledge alerts', 'schedule a review', 'refresh the data', 'message the team', 'view details'];

const settingsSections = ['profile details', 'notification preferences', 'billing and payment method', 'privacy controls', 'connected apps', 'language and region', 'appearance', 'two-factor authentication', 'team members and roles', 'data export', 'default reminders', 'email digest frequency', 'accessibility options', 'shipping addresses'];
const dangerActions = ['delete the account', 'close the account', 'reset all data', 'cancel the subscription', 'transfer ownership', 'revoke every API key'];
const settingsApps = ['member app', 'booking app', 'admin console', 'customer portal', 'staff scheduler', 'donor portal', 'parent portal', 'volunteer app', 'inventory tool', 'loyalty app'];

const compareThings = [['two membership plans', 'monthly versus annual'], ['three pricing tiers', 'basic, pro, and studio'], ['two delivery options', 'standard versus express'], ['two venues', 'the hall versus the garden'], ['three laptops for the office', 'budget, mid-range, and premium'], ['two insurance plans', 'basic versus comprehensive'], ['two training schedules', 'morning versus evening'], ['three coffee subscriptions', 'light, medium, and dark roast'], ['two payment processors', 'flat fee versus percentage'], ['two catering packages', 'buffet versus plated'], ['three bike models', 'commuter, gravel, and cargo'], ['two solar panel packages', 'six panels versus ten']];
const compareCriteria = ['price', 'what is included', 'cancellation terms', 'delivery time', 'support level', 'warranty', 'monthly cost', 'setup effort', 'risk', 'expected return', 'capacity', 'flexibility', 'time to value'];
const compareEndings = ['a recommendation', 'a note on which one fits a small team', 'the trade-off in one sentence', 'a recommended pick with a reason'];
const compareActions = ['choose a plan', 'request a quote', 'start a trial', 'talk to sales', 'save for later', 'compare again'];

const checkoutItems = ['two loaves of sourdough and a box of pastries', 'a tune-up and a new chain', 'three bags of coffee beans', 'a monthly membership and a guest pass', 'four tickets and a parking pass', 'a repair deposit and a shipping label', 'a beginner kit and two lessons', 'six jars of hot sauce', 'a print and a frame', 'a season pass and a locker rental', 'a used camera and a strap', 'a gift card and a mug'];
const checkoutShip = ['shipping address fields', 'a pickup time selector', 'delivery address fields and a delivery window', 'a choice between pickup and delivery', 'shipping details and a gift note'];
const checkoutExtras = ['a promo code field', 'an order total with tax', 'a tip selector', 'an estimated delivery date', 'the order subtotal, tax, and total', 'a summary of the cart'];
const checkoutActions = ['place-order button', 'pay now button', 'confirm purchase button', 'complete booking button', 'reserve and pay button'];

const freeform = [
  'Mission control for my sourdough starter: fermentation progress, feeding schedule, rise metrics, and an emergency deflation alert.',
  'Mission control for my model rocket launch: count down, engine status, and an emergency abort button.',
  'A mood tracker for my houseplant Gerald, who is dramatic. Track watering, sunlight drama, and overall vibes, and include a way to log an apology to Gerald.',
  'A mood tracker for my cat, with today\'s vibe, meals logged, nap count, and a button to record a grievance.',
  'A trip planner for a weekend in Lisbon: three days, a budget bar, a packing checklist as tags, and a book-hotel action.',
  'A recipe card for grandma\'s chili with ingredients as tags, steps as text, a spice-level badge, and a start-cooking button.',
  'A leaderboard for an office ping-pong ladder with the top five players, win streaks, and a challenge button.',
  'A daily standup summary for a four-person team: yesterday, today, blockers, and a mark-as-read button.',
  'A booking confirmation for a kayak rental: date, time, number of boats, weather note, and a cancel option.',
  'A garden bed planner: what is planted, days to harvest, watering status, and an add-plant action.',
  'A study tracker for the bar exam: hours this week, topics covered as tags, confidence per topic, and a log-session button.',
  'A puppy training log: commands learned, accidents this week, treat inventory, and a celebrate-milestone button.',
  'A home energy monitor: solar generated today, grid usage, battery level, and an alert when the battery is low.',
  'A wedding seating dashboard: tables filled, RSVPs pending, dietary counts, and a send-reminders action.',
  'A reading list with three books in progress, pages left, a mood tag per book, and a button to add a book.',
  'A marathon training week: runs completed, total miles, a long-run progress bar, and a rest-day toggle described as a button.',
  'An aquarium status panel: water temperature, pH, last water change, fish count, and a feed-now action.',
  'A band rehearsal planner: next session, setlist as tags, who is confirmed, and a send-reminder button.',
  'A moving-day checklist: boxes packed, rooms done, truck arrival time, and an alert about the piano.',
  'A volunteer shift board for a food bank: shifts today, spots open, a low-coverage warning, and a claim-shift button.',
  'A ski day planner: lifts open, snow report, a hot chocolate budget metric, and a book-lesson action.',
  'A bee hive inspection log: hive health, honey estimate, queen sighted badge, and a log-inspection button.',
  'A science fair project tracker: hypothesis, materials as tags, days until judging, and a submit-abstract button.',
  'A community fridge dashboard: stock level, last restock, most-needed items as tags, and a donate-now action.',
  'A tiny house build tracker: phases with progress bars, budget used, next inspection date, and a blocker alert.',
  'A chess club ladder: top players, games this month, a rising-star badge, and a challenge action.',
  'A podcast episode planner: episode title, guests as tags, recording date, a script-status badge, and a publish button.',
  'A sailing trip log: distance today, wind, crew as tags, a low-fuel warning, and a log-entry action.',
  'A mushroom grow tent monitor: humidity, temperature, days since inoculation, contamination alert, and a mist-now button.',
  'A hospice volunteer schedule: visits this week, families served, a training-due badge, and a request-swap button.',
  'A museum gift shop flash-sale banner page: featured items as tags, discount metric, hours left, and a shop-now button.',
  'A neighborhood watch bulletin: recent reports as text, a patrol schedule, an urgent alert, and a report-incident button.',
  'An arcade high-score board: top games, tokens sold today, a machine-out-of-order alert, and a refill-tokens action.',
  'A dance recital run-of-show: acts in order, costume-ready badges, minutes remaining, and a start-act button.',
  'A tea tasting notes page: three teas with aroma and flavor text, a rating badge each, and a save-notes button.',
  'A comic pull-list page: this week\'s issues as tags, subtotal, a sold-out warning, and a reserve button.',
  'A plumbing job card: customer, address, problem description, parts as tags, a parts-delayed alert, and a mark-complete button.',
  'A ferry departure board: next three departures, capacity bars, a weather delay alert, and a buy-ticket action.',
  'An astronomy night plan: targets tonight as tags, cloud cover metric, moon phase badge, and a start-session button.',
  'A ceramics kiln schedule: firings this week, kiln temperature, a load-ready badge, and a book-slot button.',
  'A goal page for learning Spanish: streak, words learned, minutes today, a level badge, and a practice-now button.',
  'A car maintenance log: mileage, last oil change, tire pressure metrics, a service-due alert, and a book-service button.',
  'A baby sleep tracker: naps today, longest stretch, a fussy badge, notes, and a log-nap button.',
  'A freelance invoice summary: outstanding total, overdue count, recent clients as tags, and a send-reminders action.',
  'A rooftop garden weather card: temperature, rain chance, wind warning, and a cover-the-tomatoes button.',
  'A film festival day schedule: screenings with times, a sold-out badge, a venue-change alert, and a get-tickets action.',
  'A blood donation drive board: donors today, units collected, a goal progress bar, and a sign-up button.',
  'A power outage status page: areas affected, estimated restoration, a safety alert, and a report-outage button.',
  'A hackathon team page: members as tags, hours left, submission status badge, and a submit-project button.',
  'A bakery morning prep list: doughs proofing with progress bars, oven temperature, a low-flour warning, and a start-bake button.',
  'A campsite check-in card: site number, nights booked, fire-ban alert, quiet hours text, and a check-in button.',
  'A fantasy football matchup: projected points for two teams, a key-injury alert, and a set-lineup action.',
  'A language exchange match page: partner name, shared interests as tags, next call time, and a message button.',
  'A homebrew batch log: gravity readings, days fermenting, temperature, a stuck-fermentation warning, and a bottle-now button.',
  'A birdwatching trip summary: species seen as tags, rare-sighting badge, distance walked, and a log-sighting action.',
  'A vintage camera repair ticket: camera model, fault description, parts status, an estimate metric, and an approve-repair button.',
  'A drone flight checklist: battery level, wind, airspace badge, a no-fly warning, and a start-flight button.',
  'A tutoring progress report: sessions completed, topics mastered as tags, a confidence bar, and a schedule-next button.',
  'A dog park meetup page: dogs attending as tags, weather, a muddy-conditions alert, and an RSVP button.',
  'A laundromat machine status board: washers and dryers free, average cycle time, an out-of-order alert, and a notify-me button.',
];

const requests = [];
const add = (family, request) => { if (!requests.some((r) => r.request === request)) requests.push({ family, request }); };

const formTemplates = [
  () => `A ${pick(formTone)} ${pick(formKinds)} form for ${pick(domains)}: ${join(some(formFields, 3, 7))}, with a ${pick(submitLabels)}.`,
  () => `${pick(domains).replace(/^(a|an|the) /, (m) => m[0].toUpperCase() + m.slice(1))} needs a ${pick(formKinds)} form asking for ${join(some(formFields, 3, 6))}. Keep it ${pick(formTone)} and end with a ${pick(submitLabels)}.`,
  () => `Build a ${pick(formKinds)} form: ${join(some(formFields, 4, 7))}. ${pick(['One card, clear labels.', 'Group related fields.', 'Nothing fancy.', 'Short intro text at the top.'])} Include a cancel button and a ${pick(submitLabels)}.`,
];
const chatTemplates = [
  () => { const [a, b] = pick(chatParties); return `A ${pick(['customer support', 'help desk', 'front desk', 'booking', 'support'])} chat at ${pick(domains)}: ${pick(chatLength)} between ${a} and ${b} about ${pick(chatTopics)}, ending with ${pick(chatEndings)}, plus a reply box and send button.`; },
  () => { const [a, b] = pick(chatParties); return `A chat transcript where ${a} asks ${b} at ${pick(domains)} about ${pick(chatTopics)}. ${pick(chatLength)[0].toUpperCase() + pick(chatLength).slice(1)}, ${pick(chatEndings)}, and a way to type a reply.`; },
];
const dashTemplates = [
  () => `A ${pick(dashKinds)} for ${pick(domains)}: ${join(some(dashMetrics, 3, 5))}, ${pick(dashExtras)}, and actions to ${pick(dashActions)} or ${pick(dashActions)}.`,
  () => `An at-a-glance ${pick(dashKinds)} for ${pick(domains)} showing ${join(some(dashMetrics, 3, 4))}. Add ${pick(dashExtras)} and a button to ${pick(dashActions)}.`,
];
const settingsTemplates = [
  () => `A settings page for ${pick(domains)}'s ${pick(settingsApps)}: ${join(some(settingsSections, 2, 4))}, and a clearly separated danger zone to ${pick(dangerActions)}.`,
  () => `Account settings for the ${pick(settingsApps)} of ${pick(domains)}, covering ${join(some(settingsSections, 3, 4))}, with a save button and a danger zone that can ${pick(dangerActions)}.`,
];
const compareTemplates = [
  () => { const [things, detail] = pick(compareThings); return `Compare ${things} for ${pick(domains)} (${detail}) on ${join(some(compareCriteria, 2, 4))}, with ${pick(compareEndings)} and buttons to ${pick(compareActions)} or ${pick(compareActions)}.`; },
  () => { const [things, detail] = pick(compareThings); return `A side-by-side comparison of ${things}, ${detail}, for ${pick(domains)}: ${join(some(compareCriteria, 3, 4))}, ending with ${pick(compareEndings)} and a ${pick(compareActions)} action.`; },
];
const checkoutTemplates = [
  () => `A checkout review screen for ${pick(domains)}: ${pick(checkoutItems)}, ${pick(checkoutShip)}, ${pick(checkoutExtras)}, and a ${pick(checkoutActions)}.`,
  () => `An order review page for ${pick(domains)}'s online shop with ${pick(checkoutItems)} in the cart, ${pick(checkoutShip)}, ${pick(checkoutExtras)}, and a ${pick(checkoutActions)}.`,
];

const perFamily = 50;
for (const [family, templates] of [['form', formTemplates], ['chat', chatTemplates], ['dashboard', dashTemplates], ['settings', settingsTemplates], ['compare', compareTemplates], ['checkout', checkoutTemplates]]) {
  let guard = 0;
  while (requests.filter((r) => r.family === family).length < perFamily && guard++ < 2000) add(family, pick(templates)());
}
for (const request of freeform) add('freeform', request);
// Extra free-form variety from a small combinatorial generator.
const ffSubjects = ['my sourdough starter', 'the office plant wall', 'a backyard chicken coop', 'a kids\' lemonade stand', 'a community theater production', 'a robot vacuum fleet', 'a school garden', 'a beach cleanup', 'a family reunion', 'a garage sale', 'a rooftop beehive', 'a book club', 'a charity bike ride', 'a snow day', 'a coffee cart', 'a treehouse build', 'a night market stall', 'a canoe trip', 'a pumpkin patch', 'a street piano'];
const ffShapes = ['mission control for', 'a status board for', 'a daily log for', 'a progress page for', 'a planning board for', 'a summary card for', 'a tracker for'];
const ffBits = ['a countdown', 'a progress bar', 'two or three key metrics', 'a warning when something is wrong', 'a short note', 'tags for the people involved', 'a status badge', 'a checklist as tags', 'a budget metric', 'a weather note'];
const ffActions = ['a log-it button', 'an emergency button', 'a share action', 'a mark-done button', 'a call-for-help action', 'a start button'];
let guard = 0;
while (requests.filter((r) => r.family === 'freeform').length < 150 && guard++ < 2000) add('freeform', `${pick(ffShapes)[0].toUpperCase() + pick(ffShapes).slice(1)} ${pick(ffSubjects)}: ${join(some(ffBits, 3, 4))}, and ${pick(ffActions)}.`.replace(/^(\w+) control for/, (m) => m));

// Hold-out: the six workbench sparks plus a stratified sample, never trained on.
const sparks = [
  'A patient intake form for a family clinic: full name, date of birth, phone, email, reason for visit, current medications, and known allergies, with a submit action. Deliberately plain and professional.',
  'A customer support chat about a delayed order: a short back-and-forth conversation between the customer and the support agent, ending with a proposed solution, plus a reply box and send button.',
  'A status dashboard for a website redesign project: overall progress, budget used, open tasks, a blockers alert, and actions to view the board or export a report.',
  'An account settings page: profile details, notification preferences, and a clearly separated danger zone with a delete-account action.',
  'A checkout review screen for a small web shop: a summary of the ordered items, shipping details fields, the order total, and a place-order action.',
  'Mission control for my sourdough starter: fermentation progress, feeding schedule, rise metrics, and an emergency deflation alert.',
];
const sparkFamilies = ['form', 'chat', 'dashboard', 'settings', 'checkout', 'freeform'];
// The blog's showcase prompts are held out too, so their before/after is never contaminated by training.
const showcase = [freeform[1], freeform[2]];
const holdout = new Set([...sparks, ...showcase]);
for (const r of requests) if (holdout.has(r.request)) r.split = 'eval';
sparks.forEach((request, i) => { if (!requests.some((r) => r.request === request)) requests.push({ family: sparkFamilies[i], request, split: 'eval' }); });
for (const family of ['form', 'chat', 'dashboard', 'settings', 'compare', 'checkout', 'freeform']) {
  const pool = requests.filter((r) => r.family === family && r.split !== 'eval');
  const want = family === 'freeform' ? 14 : 6;
  for (const r of some(pool, want, want)) r.split = 'eval';
}
for (const r of requests) r.split ??= 'train';

const lines = requests.map((r, i) => JSON.stringify({ id: `p${String(i + 1).padStart(3, '0')}`, family: r.family, split: r.split, request: r.request }));
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join('\n') + '\n');
const count = (f) => requests.filter(f).length;
console.error(`wrote ${requests.length} requests to ${OUT} · train ${count((r) => r.split === 'train')} · eval ${count((r) => r.split === 'eval')}`);
for (const family of ['form', 'chat', 'dashboard', 'settings', 'compare', 'checkout', 'freeform']) console.error(`  ${family.padEnd(10)} train ${String(count((r) => r.family === family && r.split === 'train')).padStart(3)} · eval ${count((r) => r.family === family && r.split === 'eval')}`);
